name: build

on:
  workflow_dispatch: # Manually tiggering the job
  push: # automatically tiggering the job
    branches:
      - main
 # pull_request: # trigger when a PR is raised to Main brnach
 #   branches:
 #     - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:    
      - name: Check out source code
        uses: actions/checkout@v3  
      - name: Run ScanCentral SAST Scan
        uses: fortify/github-action/sc-sast-scan@4f2bcce01b032ad63967b05ff553f49253944d4f
       # env:
         # SSC_URL: ${{secrets.SSC_URL}}
         # SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          #SC_SAST_TOKEN: ${{secrets.CLIENT_AUTH_TOKEN}}
          # EXTRA_SC_SAST_LOGIN_OPTS: --socket-timeout=60s
          # SSC_APPVERSION: MyApp:MyVersion
          # EXTRA_PACKAGE_OPTS: -bf custom-pom.xml
          # SC_SAST_SENSOR_VERSION: 23.2
          # DO_WAIT: true
          # DO_EXPORT: true
          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
